version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user

