version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
    overwrite: yes  # ✅ This allows overwriting existing files

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
