name: Auto-Merge Test to Main

on:
  push:
    branches:
      - test  # Trigger action when code is pushed to 'test'
  workflow_dispatch:

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}  # Use Personal Access Token instead of default GitHub token

      - name: Configure Git
        run: |
          git config --global user.email "jaysolanki0422@gmail.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Merge Test into Main
        run: |
          git checkout main
          git pull origin main
          git merge origin/test --no-edit || { echo "Merge conflict detected. Aborting merge."; git merge --abort; exit 1; }
          git push origin main
