name: Auto-Merge Test to Main

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git
        run: |
          git config --global user.email "jaysolanki0422@gmail.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Fetch latest branches
        run: |
          git fetch --all

      - name: Ensure test branch is up-to-date
        run: |
          git checkout test
          git pull origin test

      - name: Merge Test into Main
        run: |
          git checkout main
          git pull origin main
          
          # Try merging test into main
          if git merge origin/test --no-edit; then
            echo "Merge successful."
          else
            echo "Merge conflict detected. Resolving automatically..."
            git merge --abort  # Abort the failed merge
            git merge -X theirs origin/test --no-edit  # Automatically resolve conflicts by keeping 'test' changes
          fi
          
          git push origin main
