name: Auto-Merge Test to Main

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "jaysolanki0422@gmail.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Fetch all branches
        run: git fetch --all

      - name: Ensure test branch is up-to-date
        run: |
          git checkout test
          git pull origin test

      - name: Merge Test into Main
        run: |
          git checkout main
          git pull origin main
          git merge test --no-edit || { echo "Merge conflict detected. Aborting merge."; git merge --abort; exit 1; }
          git push origin main
